In [8]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [9]:
y2015 = pd.read_csv('LoanStats3d.csv', skipinitialspace=True, header=1)

C:\Users\Fazel\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3057: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
pd.set_option('display.max_columns', None)
y2015.head()

id   member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  68009401  72868139.0    16000.0      16000.0          16000.0   60 months   
1  68354783  73244544.0     9600.0       9600.0           9600.0   36 months   
2  68466916  73356753.0    25000.0      25000.0          25000.0   36 months   
3  68466961  73356799.0    28000.0      28000.0          28000.0   36 months   
4  68495092  73384866.0     8650.0       8650.0           8650.0   36 months   

  int_rate  installment grade sub_grade              emp_title emp_length  \
0   14.85%       379.39     C        C5  Bookkeeper/Accounting  10+ years   
1    7.49%       298.58     A        A4                   tech    8 years   
2    7.49%       777.55     A        A4          Sales Manager  10+ years   
3    6.49%       858.05     A        A2         Senior Manager  10+ years   
4   19.89%       320.99     E        E3   Program Coordinator     8 years   

  home_ownership  annual_inc verification_status   issue_d loan_status  \
0       MORTGAGE     48000.0        Not Verified  Dec-2015     Current   
1       MORTGAGE     60000.0        Not Verified  Dec-2015     Current   
2       MORTGAGE    109000.0        Not Verified  Dec-2015  Fully Paid   
3       MORTGAGE     92000.0        Not Verified  Dec-2015     Current   
4           RENT     55000.0            Verified  Dec-2015  Fully Paid   

  pymnt_plan                                                url desc  \
0          n  https://lendingclub.com/browse/loanDetail.acti...  NaN   
1          n  https://lendingclub.com/browse/loanDetail.acti...  NaN   
2          n  https://lendingclub.com/browse/loanDetail.acti...  NaN   
3          n  https://lendingclub.com/browse/loanDetail.acti...  NaN   
4          n  https://lendingclub.com/browse/loanDetail.acti...  NaN   

              purpose                    title zip_code addr_state    dti  \
0         credit_card  Credit card refinancing    297xx         SC  33.18   
1         credit_card  Credit card refinancing    299xx         SC  22.44   
2  debt_consolidation       Debt consolidation    226xx         VA  26.02   
3  debt_consolidation       Debt consolidation    275xx         NC  21.60   
4  debt_consolidation       Debt consolidation    462xx         IN  25.49   

   delinq_2yrs earliest_cr_line  inq_last_6mths  mths_since_last_delinq  \
0          0.0         Jun-1991             0.0                    33.0   
1          0.0         Jun-1996             0.0                     NaN   
2          0.0         Dec-2001             1.0                     NaN   
3          0.0         May-1984             0.0                    42.0   
4          0.0         Mar-2005             4.0                     NaN   

   mths_since_last_record  open_acc  pub_rec  revol_bal revol_util  total_acc  \
0                     2.0      11.0      2.0    19108.0      29.6%       19.0   
1                     NaN       7.0      0.0     7722.0      59.4%        9.0   
2                     NaN       9.0      0.0    20862.0      54.3%       19.0   
3                     NaN      16.0      0.0    51507.0      64.5%       24.0   
4                    30.0      18.0      1.0     9568.0        46%       19.0   

  initial_list_status  out_prncp  out_prncp_inv  total_pymnt  total_pymnt_inv  \
0                   w   13668.88       13668.88      4519.68          4519.68   
1                   w    6635.69        6635.69      3572.97          3572.97   
2                   w       0.00           0.00     26224.23         26224.23   
3                   w   19263.77       19263.77     10271.36         10271.36   
4                   w       0.00           0.00      9190.49          9190.49   

   total_rec_prncp  total_rec_int  total_rec_late_fee  recoveries  \
0          2331.12        2188.56                 0.0         0.0   
1          2964.31         608.66                 0.0         0.0   
2         25000.00        1224.23                 0.0         0.0   
3          8736.23     

In [10]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)

cross_val_score(rfc, X, Y, cv=5)

MemoryError: 

In [11]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3


In [10]:
print('id type: {}'.format(type(y2015.id)))
print('int_rate type: {}'.format(type(y2015.int_rate)))

id type: <class 'pandas.core.series.Series'>
int_rate type: <class 'pandas.core.series.Series'>


In [12]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [13]:
y2015.tail()

id   member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
421092  36271333.0  38982739.0    13000.0      13000.0          13000.0   
421093  36490806.0  39222577.0    12000.0      12000.0          12000.0   
421094  36271262.0  38982659.0    20000.0      20000.0          20000.0   
421095         NaN         NaN        NaN          NaN              NaN   
421096         NaN         NaN        NaN          NaN              NaN   

              term  int_rate  installment grade emp_length  ...  \
421092   60 months     15.99       316.07     D    5 years  ...   
421093   60 months     19.99       317.86     E     1 year  ...   
421094   36 months     11.99       664.20     B  10+ years  ...   
421095         NaN       NaN          NaN   NaN        NaN  ...   
421096         NaN       NaN          NaN   NaN        NaN  ...   

       num_tl_90g_dpd_24m  num_tl_op_past_12m pct_tl_nvr_dlq percent_bc_gt_75  \
421092                0.0                 3.0          100.0             50.0   
421093                1.0                 2.0           95.0             66.7   
421094                0.0                 1.0          100.0             50.0   
421095                NaN                 NaN            NaN              NaN   
421096                NaN                 NaN            NaN              NaN   

       pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort  \
421092                  1.0       0.0         51239.0           34178.0   
421093                  0.0       0.0         96919.0           58418.0   
421094                  0.0       1.0         43740.0           33307.0   
421095                  NaN       NaN             NaN               NaN   
421096                  NaN       NaN             NaN               NaN   

        total_bc_limit  total_il_high_credit_limit  
421092         10600.0                     33239.0  
421093          9700.0                     69919.0  
421094         41700.0                         0.0  
421095             NaN                         NaN  
421096             NaN                         NaN  

[5 rows x 103 columns]

In [14]:
# Remove two summary rows at the end that don't actually contain data.
y2015 = y2015[:-2]

In [41]:
print(y2015.loan_status.unique())

['Current' 'Fully Paid' 'Charged Off' 'Late (31-120 days)'
 'In Grace Period' 'Default' 'Late (16-30 days)']


In [15]:
y2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421095 entries, 0 to 421094
Columns: 103 entries, id to total_il_high_credit_limit
dtypes: float64(87), object(16)
memory usage: 330.9+ MB


In [15]:
pd.get_dummies(y2015)

id   member_id  loan_amnt  funded_amnt  funded_amnt_inv  \
0       68009401.0  72868139.0    16000.0      16000.0          16000.0   
1       68354783.0  73244544.0     9600.0       9600.0           9600.0   
2       68466916.0  73356753.0    25000.0      25000.0          25000.0   
3       68466961.0  73356799.0    28000.0      28000.0          28000.0   
4       68495092.0  73384866.0     8650.0       8650.0           8650.0   
5       68506798.0  73396623.0    23000.0      23000.0          23000.0   
6       68566886.0  73456723.0    29900.0      29900.0          29900.0   
7       68577849.0  73467703.0    18000.0      18000.0          18000.0   
8       66310712.0  71035433.0    35000.0      35000.0          35000.0   
9       68476807.0  73366655.0    10400.0      10400.0          10400.0   
10      68341763.0  72928789.0    20000.0      20000.0          20000.0   
11      68356421.0  73246236.0    22400.0      22400.0          22400.0   
12      68426545.0  73316365.0    16000.0      16000.0          16000.0   
13      68407277.0  73297111.0     3600.0       3600.0           3600.0   
14      68355089.0  73244858.0    24700.0      24700.0          24700.0   
15      68466926.0  73356763.0    10000.0      10000.0          10000.0   
16      68338832.0  73542831.0     1400.0       1400.0           1400.0   
17      68426831.0  73316657.0    11950.0      11950.0          11950.0   
18      66624733.0  71350547.0    18000.0      18000.0          18000.0   
19      68616873.0  73519699.0     8000.0       8000.0           8000.0   
20      67275481.0  72077199.0    20000.0      20000.0          20000.0   
21      68476668.0  73366513.0    20000.0      20000.0          20000.0   
22      68476702.0  73366548.0    28000.0      28000.0          28000.0   
23      68436666.0  73326493.0     5000.0       5000.0           5000.0   
24      68596180.0  73485987.0    20000.0      20000.0          20000.0   
25      67849662.0  72708407.0     4225.0       4225.0           4225.0   
26      68526883.0  73416719.0    15000.0      15000.0          15000.0   
27      68607141.0  73509983.0    17600.0      17600.0          17600.0   
28      68476715.0  73366561.0     6000.0       6000.0           6000.0   
29      67715283.0  72569997.0    16000.0      16000.0          16000.0   
...            ...         ...        ...          ...              ...   
421065  36631385.0  39374138.0    13000.0      13000.0          13000.0   
421066  36231083.0  38942474.0    15000.0      15000.0          15000.0   
421067  36691397.0  39434133.0    20000.0      20000.0          20000.0   
421068  36743377.0  39486112.0     4200.0       4200.0           4200.0   
421069  36331554.0  39042967.0    26950.0      26950.0          26950.0   
421070  36460697.0  39182359.0    23000.0      23000.0          23000.0   
421071  35773415.0  38468842.0    18700.0      18700.0          18700.0   
421072  36250801.0  38962184.0     6000.0       6000.0           6000.0   
421073  36371802.0  39103231.0    15000.0      15000.0          15000.0   
421074  36440728.0  39152101.0    25000.0      25000.0          25000.0   
421075  36361815.0  39093260.0    26500.0      26500.0          26500.0   
421076  35591131.0  38288343.0    25000.0      25000.0          25000.0   
421077  36201871.0  38913321.0    21000.0      21000.0          21000.0   
421078  36381756.0  39013193.0     8000.0       8000.0           8000.0   
421079  36231724.0  38943173.0    12000.0      12000.0          12000.0   
421080  36301729.0  39023153.0    10000.0      10000.0          10000.0   
421081  36250208.0  38961532.0    13150.0      13150.0          13150.0   
421082  36241316.0  38952731.0     6225.0       6225.0           6225.0   
421083  36231718.0  38943165.0    10775.0      10775.0          10775.0   
421084  36381704.0  39013139.0     7000.0       7000.0           7000.0   
421085  36421485.0  39142898.0     4000.0       4000.0           4000.0   
421086  35094480.0  37777829.0     7500.0

In [16]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

C:\Users\Fazel\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Fazel\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Fazel\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Fazel\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Fazel\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:245: F

array([0.9794353 , 0.98059889, 0.98169124, 0.98180998, 0.97254809,
       0.97703633, 0.94841958, 0.98064547, 0.98002707, 0.98085783])

## DRILL: Third Attempt
So here's your task. Get rid of as much data as possible without dropping below an average of 90% accuracy in a 10-fold cross validation.

You'll want to do a few things in this process. First, dive into the data that we have and see which features are most important. This can be the raw features or the generated dummies. You may want to use PCA or correlation matrices.

Can you do it without using anything related to payment amount or outstanding principal? How do you know?

## PCA:

In [24]:
# Import and run PCA model 
from sklearn.decomposition import PCA
pca = PCA(n_components=20)
pca.fit(X)
X_pca = pca.transform(X)

In [25]:
# Test PCA on forest
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_pca, Y, cv=10)

array([0.83619482, 0.95609223, 0.95435872, 0.95585476, 0.95877464,
       0.95093802, 0.95390534, 0.95236173, 0.95340442, 0.91958391])

In [20]:
pca = PCA(n_components=12)
pca.fit(X)
X_pca = pca.transform(X)

In [22]:
import warnings
warnings.filterwarnings('ignore')
# Test PCA on forest
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_pca, Y, cv=10)

array([0.69732374, 0.79257201, 0.81729239, 0.79900739, 0.69672287,
       0.70113987, 0.56543732, 0.53815099, 0.54876861, 0.571225  ])

Using PCA dimensionality reduction, almost 90% accuracy can be maintained by reducing the data to 20 principle components. Less than 20 will result for sure in <90% accuracy.

In [27]:
numerical = y2015.select_dtypes(include=['float64']).columns
numerical

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'int_rate', 'installment', 'annual_inc', 'dti', 'delinq_2yrs',
       'inq_last_6mths', 'mths_since_last_delinq', 'mths_since_last_record',
       'open_acc', 'pub_rec', 'revol_bal', 'total_acc', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_amnt',
       'collections_12_mths_ex_med', 'mths_since_last_major_derog',
       'policy_code', 'annual_inc_joint', 'dti_joint', 'acc_now_delinq',
       'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m', 'open_il_6m',
       'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il', 'total_bal_il',
       'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc', 'all_util',
       'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'acc_open_past_24mths', 'avg_cur_bal', 'bc_open_to_buy', 'bc_util',
       'chargeoff_wit

In [28]:
# Remove all columns related to payment amount and outstanding principal 
columns = ['out_prncp', 'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv',
       'total_rec_prncp', 'total_rec_int','last_pymnt_amnt']

X_reducted = X.drop(columns=columns)

# Rerun model with reduced data set
rfc = ensemble.RandomForestClassifier()
cross_val_score(rfc, X_reducted, Y, cv=10)

array([0.90995227, 0.93092066, 0.91823989, 0.91277813, 0.91802422,
       0.93027784, 0.83647201, 0.94281508, 0.92832546, 0.73072721])

Yes, accuracy >90% can be achieved if payment amount and outstanding principal information is excluded from the dataset.